= Titre

== Avant Propos
Pour comencer ce livre,ilvous faut connaitre les personage de l histoire.

Les voici:      




    violette                    Rose                    léon(appelé Lion)                       Sacha
    10 ans 3/4                  11ans                        10ans                             10ans1/2
  
  
  
  
  
  
  
  
  
  
  
                                                             
  
  
   
  
  
  
  
  adore la trotinette        adore lire          adore la nature et les animaux             adore le vélo et le bateau 
  
  
  
  
 
  
  
   
  
==  Chapitre1


Violette,Rose,Léon et Sacha en avait marre du confinement les cours à distance,les magasins,les cinémas, les thèâtres et les sales 
d'escalade fermés et le faite de ne pas pouvoir sortir.Un soir,ils décidèrent d'aller au parc pour se dégourdir les pattes,en rentrent ils
escaladèrent une maison parce que comme les sales d' escalades etait fermés ils etait content d' escalader un peut tout .Soudain, un  cri 
retentits c'etait Léon qui se faisait tirer par il ne savait quoi,après ce fut au tour de Sacha, puis de Rose et enfin de Violette.On les
emmena dans la maison,ou on les enferma dans une pièce très sombre qu'on ferma a triple tours. ils entendirent une voix qui disait:
"je ne vous ouvrirai pas de si tot!"ils urent du mal a dormir car ils se demandaient ce qu' il alait leurs arriver. Mais ils éssayaiérent
quand même de dormir,vers mi nuit ils se firent révéillé par un craquement sonor, c' était une dale qui tombait elle liberait un passage.
ils décidairent de s' y engager, et remirent avec precaution la dale â l' endroit ôu ellez se trouvait avant. le passsage était étroit et 
sombre. ils durent avencer â quatre pattes pour ne pas se cogner la tète sur le plafon de roche. Au bout d' â peu près cinq quilomètre,ils
purent marcher debout    
Feb 17, 2021, 12:59:56
