= Titre

== Avant Propos
Pour comencer ce livre,ilvous faut connaitre les personage de l histoire.

Les voici:      




    violette                    Rose                    léon(appelé Lion)                       Sacha
    10 ans 3/4                  11ans                        10ans                             10ans1/2
  
  
  
  
  
  
  
  
  
  
  
                                                             
  
  
  
  
  
  
  
  adore la trotinette             adore lire                adore la nature et les animaux             adorele vélo et le bateau 
  
  
  
  
 
  
  
   
  
==  Chapitre1


Violette,Rose,Léon et Sacha en avait marre du confinement les cours à distance,les magasins,les cinémas, les thèâtres et les sales 
d'escalade fermés et le faite de ne pas pouvoir sortir.Un soir,ils décidèrent d'aller au parc pour se dégourdir les pates,en rentrent ils
escaladèrent une maison parce que comme les sales d' escalades etait fermés ils etait content d' escalader un peut tout .Soudain, un  cri 
retentits'etait Léon qui se faisait tirer par il ne savait quoi,apres ce fut au tour de Sacha, puis de Rose et enfin de Violette.On les
emmena dans la maison,ou on les enferma dans une pièce très sombre qu'on ferma a triple tours. 
ils entendirent
